### ISSUE TITLE
is it possible to use it without docker 

### ISSUE THREAD

**Issue by N30Z3N** [meanii/downly#2]
I wish to run on a server but don't want to use docker any other way ?

**Comment by meanii** [comment]
yes, you can use it without docker 

follow these steps
1. deploy your postgresql instance 
2. install ffmpeg
3. install dependencies 
`pip install -r requirements.txt`
4. python3 -m downly

**Comment by N30Z3N** [comment]
what to write in config.yaml any example

**Comment by meanii** [comment]
```yaml
downly:
  app_name: "downly"

  telegram:
    api_id: "your_telegram_api_id"
    api_hash: "your_telegram_api_hash"
    bot_token: "your_telegram_bot_token"

  configs:
    owner: "your_telegram_bot_owner_userid"
    channel_id: "your_telegram_channel_id"
    public: "true"
    cobalt_base_url: "https://co.wuk.sh"

  database:
    postgres_url: "postgres://downly:downly@localhost:5432/downly"
    redis_url: "redis://localhost:6379"

```

**Comment by meanii** [comment]
> what to write in config.yaml any example

```yaml
downly:
  app_name: "downly"

  telegram:
    api_id: "your_telegram_api_id"
    api_hash: "your_telegram_api_hash"
    bot_token: "your_telegram_bot_token"

  configs:
    owner: "your_telegram_bot_owner_userid"
    channel_id: "your_telegram_channel_id"
    public: "true"
    cobalt_base_url: "https://co.wuk.sh"

  database:
    postgres_url: "postgres://downly:downly@localhost:5432/downly"
    redis_url: "redis://localhost:6379"
```
